name: sepp_note
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  flutter_staggered_grid_view: ^0.6.1
  flutter_sound: ^9.2.12
dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
